// Sverigequiz – kapitel 5
// Lag och rätt
// Källa: Sverige i fokus 2026-1, korrigerad 2026-08-10

(() => {
  const replacementChapters = new Set([5]);

  window.SVERIGEQUIZ_QUESTIONS =
    window.SVERIGEQUIZ_QUESTIONS.filter(
      q => !replacementChapters.has(q.chapter)
    );

  const chapterQuestions = [
    {
      id: "ch5-01",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattssakerhet",
      difficulty: "easy",
      question: "Vad betyder rättssäkerhet?",
      options: [
        "Att alla behandlas lika inför lagen och har rätt till en rättvis rättegång",
        "Att regeringen bestämmer hur domstolarna ska döma",
        "Att bara svenska medborgare skyddas av lagen",
        "Att alla brott alltid leder till fängelse"
      ],
      correctIndex: 0,
      explanationSv: "Rättssäkerhet innebär att alla behandlas lika inför lagen och har rätt till en rättvis rättegång.",
      studyTitle: "Rättssäkerhet",
      studyText: "Rättssäkerhet innebär att alla behandlas lika inför lagen och har rätt till en rättvis rättegång.",
      studyRemember: "Rättssäkerhet = lika inför lagen och rättvis rättegång.",
      section: "Lag och rätt",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-02",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "easy",
      question: "Hur många grundlagar har Sverige?",
      options: [
        "Fyra",
        "Tre",
        "Fem",
        "Sex"
      ],
      correctIndex: 0,
      explanationSv: "Sverige har fyra grundlagar.",
      studyTitle: "Sveriges grundlagar",
      studyText: "Sverige har fyra grundlagar: regeringsformen, tryckfrihetsförordningen, yttrandefrihetsgrundlagen och successionsordningen. Grundlagarna är svårare att ändra än andra lagar.",
      studyRemember: "Sverige har fyra grundlagar.",
      section: "Grundlagarna",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-03",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "medium",
      question: "Vad skiljer grundlagarna från andra lagar?",
      options: [
        "De är svårare att ändra",
        "De gäller bara under valår",
        "De gäller bara myndigheter",
        "De kan ändras av en domstol när som helst"
      ],
      correctIndex: 0,
      explanationSv: "Grundlagarna är svårare att ändra än andra lagar.",
      studyTitle: "Grundlagarna",
      studyText: "Grundlagarna är svårare att ändra än andra lagar. Sverige har fyra grundlagar.",
      studyRemember: "Grundlagarna är svårare att ändra.",
      section: "Grundlagarna",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-04",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "regeringsformen",
      difficulty: "medium",
      question: "Vad säger regeringsformen om den offentliga makten i Sverige?",
      options: [
        "All offentlig makt utgår från folket",
        "All offentlig makt utgår från regeringen",
        "All offentlig makt utgår från kungen",
        "All offentlig makt utgår från domstolarna"
      ],
      correctIndex: 0,
      explanationSv: "Regeringsformen säger att all offentlig makt i Sverige utgår från folket.",
      studyTitle: "Regeringsformen",
      studyText: "Regeringsformen säger att all offentlig makt utgår från folket, att riksdagen stiftar lagar och att regeringen styr landet.",
      studyRemember: "All offentlig makt utgår från folket.",
      section: "Regeringsformen",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-05",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "tryckfrihet",
      difficulty: "easy",
      question: "Vad skyddar tryckfrihetsförordningen?",
      options: [
        "Det fria ordet i tryckt form",
        "Rätten till sjukvård",
        "Rätten till semester",
        "Rätten att få körkort"
      ],
      correctIndex: 0,
      explanationSv: "Tryckfrihetsförordningen skyddar det fria ordet i tryckt form.",
      studyTitle: "Tryckfrihetsförordningen",
      studyText: "Tryckfrihetsförordningen skyddar det fria ordet i tryckt form. Den ger alla rätt att fritt ge ut böcker, tidningar och tidskrifter.",
      studyRemember: "Tryckfrihetsförordningen skyddar det fria ordet i tryckt form.",
      section: "Tryckfrihetsförordningen",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-06",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "yttrandefrihet",
      difficulty: "easy",
      question: "Vad ger yttrandefrihetsgrundlagen människor rätt att göra?",
      options: [
        "Uttrycka sina tankar och åsikter fritt",
        "Bestämma hur domstolar ska döma",
        "Bryta mot andra lagar",
        "Bestämma vad andra människor får säga"
      ],
      correctIndex: 0,
      explanationSv: "Yttrandefrihetsgrundlagen ger alla rätt att uttrycka sina tankar och åsikter fritt.",
      studyTitle: "Yttrandefrihetsgrundlagen",
      studyText: "Yttrandefrihetsgrundlagen ger alla rätt att uttrycka sina tankar och åsikter fritt, till exempel i radio, tv och dagstidningar.",
      studyRemember: "Yttrandefrihet = rätt att uttrycka tankar och åsikter.",
      section: "Yttrandefrihetsgrundlagen",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-07",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "yttrandefrihet",
      difficulty: "medium",
      question: "Är alla yttranden tillåtna i Sverige?",
      options: [
        "Nej, vissa yttranden är förbjudna i lag",
        "Ja, alla yttranden är alltid tillåtna",
        "Ja, om de publiceras på internet",
        "Nej, bara politiker får uttrycka åsikter offentligt"
      ],
      correctIndex: 0,
      explanationSv: "Tryck- och yttrandefriheten skyddar rätten att uttrycka åsikter, men vissa yttranden är förbjudna i lag.",
      studyTitle: "Yttrandefriheten har gränser",
      studyText: "Vissa yttranden är förbjudna i lag. Materialet nämner bland annat förtal, hets mot folkgrupp och hatbrott. Det är också förbjudet att sprida information som kan skada Sveriges säkerhet.",
      studyRemember: "Yttrandefriheten betyder inte att alla yttranden är tillåtna.",
      section: "Yttrandefrihetsgrundlagen",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-08",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "successionsordningen",
      difficulty: "easy",
      question: "Vad bestämmer successionsordningen?",
      options: [
        "Vem som ska bli kung eller drottning efter den nuvarande",
        "Hur riksdagen väljs",
        "Vilka brott som ger fängelse",
        "Hur kommunerna ska styras"
      ],
      correctIndex: 0,
      explanationSv: "Successionsordningen bestämmer vem som ska bli kung eller drottning efter den nuvarande.",
      studyTitle: "Successionsordningen",
      studyText: "Successionsordningen är den grundlag som bestämmer vem som ska bli kung eller drottning efter den nuvarande.",
      studyRemember: "Successionsordningen handlar om vem som ärver tronen.",
      section: "Successionsordningen",
      sourcePage: 16,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-09",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "allemansratt",
      difficulty: "easy",
      question: "I vilken grundlag skyddas allemansrätten?",
      options: [
        "Regeringsformen",
        "Successionsordningen",
        "Tryckfrihetsförordningen",
        "Yttrandefrihetsgrundlagen"
      ],
      correctIndex: 0,
      explanationSv: "Den svenska allemansrätten skyddas i regeringsformen.",
      studyTitle: "Allemansrätten",
      studyText: "Allemansrätten skyddas i regeringsformen och ger alla möjlighet att vara i naturen oavsett vem som äger marken.",
      studyRemember: "Allemansrätten skyddas i regeringsformen.",
      section: "Allemansrätten är skyddad i grundlagen",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-10",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "allemansratt",
      difficulty: "medium",
      question: "Vad måste man tänka på när man använder allemansrätten?",
      options: [
        "Att inte skada naturen eller störa markägaren",
        "Att bara vistas på statlig mark",
        "Att alltid fråga kommunen först",
        "Att man aldrig får sätta upp tält"
      ],
      correctIndex: 0,
      explanationSv: "Man ska vara ansvarsfull och inte skada naturen eller störa markägaren.",
      studyTitle: "Ansvar i naturen",
      studyText: "Allemansrätten ger stora möjligheter att vara i naturen, men man ska vara ansvarsfull och inte skada naturen eller störa markägaren.",
      studyRemember: "Inte skada naturen eller störa markägaren.",
      section: "Allemansrätten är skyddad i grundlagen",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-11",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "allemansratt",
      difficulty: "medium",
      question: "Vilket av detta är inte tillåtet enligt avsnittet om allemansrätten?",
      options: [
        "Att gå in i någon annans trädgård",
        "Att paddla",
        "Att cykla",
        "Att plocka bär"
      ],
      correctIndex: 0,
      explanationSv: "Det är inte tillåtet att gå in i någon annans trädgård.",
      studyTitle: "Allemansrättens gränser",
      studyText: "Det går bland annat bra att gå, cykla, paddla och plocka bär. Men det är inte tillåtet att gå på bondens åkrar, gå in i någon annans trädgård eller kasta skräp i naturen.",
      studyRemember: "Allemansrätten innebär både frihet och ansvar.",
      section: "Allemansrätten är skyddad i grundlagen",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-12",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "easy",
      question: "Vad gör Polisen som en del av rättsväsendet?",
      options: [
        "Förhindrar, utreder och bekämpar brott",
        "Stiftar Sveriges lagar",
        "Dömer personer till fängelse",
        "Bestämmer vilka lagar riksdagen ska anta"
      ],
      correctIndex: 0,
      explanationSv: "Polisen förhindrar, utreder och bekämpar brott.",
      studyTitle: "Rättsväsendet",
      studyText: "Polisen är en del av rättsväsendet och förhindrar, utreder och bekämpar brott.",
      studyRemember: "Polisen förhindrar, utreder och bekämpar brott.",
      section: "Rättsväsendet",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-13",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "medium",
      question: "Vad gör Åklagarmyndigheten enligt materialet?",
      options: [
        "Avgör om personer som misstänks för brott ska ställas inför domstol",
        "Bestämmer vilka lagar riksdagen ska anta",
        "Ansvarar för alla fängelser",
        "Utfärdar pass"
      ],
      correctIndex: 0,
      explanationSv: "Åklagarmyndigheten avgör om personer som misstänks för brott ska ställas inför en domstol.",
      studyTitle: "Åklagarmyndigheten",
      studyText: "Åklagarmyndigheten avgör om personer som misstänks för brott ska ställas inför en domstol.",
      studyRemember: "Åklagaren avgör om en misstänkt ska ställas inför domstol.",
      section: "Rättsväsendet",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-14",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "medium",
      question: "Vad ansvarar Kriminalvården bland annat för?",
      options: [
        "Fängelser och att dömda personer avtjänar sina straff",
        "Att stifta lagar",
        "Att avgöra skuld i domstol",
        "Att utfärda nationella id-kort"
      ],
      correctIndex: 0,
      explanationSv: "Kriminalvården ansvarar bland annat för fängelser och för att dömda personer avtjänar sina straff.",
      studyTitle: "Kriminalvården",
      studyText: "Kriminalvården ansvarar bland annat för fängelser och för att dömda personer avtjänar sina straff.",
      studyRemember: "Kriminalvården ansvarar bland annat för fängelser.",
      section: "Rättsväsendet",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-15",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattssakerhet",
      difficulty: "medium",
      question: "Kan regeringen eller riksdagen bestämma hur en domstol ska döma?",
      options: [
        "Nej, domstolarna är oberoende",
        "Ja, regeringen kan alltid bestämma",
        "Ja, riksdagen bestämmer i brottmål",
        "Ja, om brottet är allvarligt"
      ],
      correctIndex: 0,
      explanationSv: "Domstolarna är oberoende. Regeringen eller riksdagen kan inte bestämma hur de ska döma.",
      studyTitle: "Oberoende domstolar",
      studyText: "Domstolarna är oberoende. Regeringen eller riksdagen kan inte bestämma hur de ska döma.",
      studyRemember: "Domstolarna är oberoende.",
      section: "Rättssäkerhet",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-16",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattssakerhet",
      difficulty: "medium",
      question: "Vilken rätt har man om man anser att en dom är fel?",
      options: [
        "Man kan överklaga domen",
        "Man kan själv ändra domen",
        "Man kan kräva att regeringen ändrar domen",
        "Man måste alltid acceptera domen utan ny prövning"
      ],
      correctIndex: 0,
      explanationSv: "Rättssäkerheten innebär bland annat att man kan överklaga en dom om man anser att den är fel.",
      studyTitle: "Rätten att överklaga",
      studyText: "Rättssäkerhet innebär att alla har rätt att försvara sig med hjälp av en advokat och kan överklaga en dom om man anser att den är fel.",
      studyRemember: "En dom kan överklagas.",
      section: "Rättssäkerhet",
      sourcePage: 17,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-17",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "easy",
      question: "Hur ska en person som misstänks för brott betraktas innan personen har dömts?",
      options: [
        "Som oskyldig",
        "Som skyldig",
        "Som dömd",
        "Som vittne"
      ],
      correctIndex: 0,
      explanationSv: "En misstänkt person ska betraktas som oskyldig tills personen har dömts för brottet.",
      studyTitle: "Oskyldig tills man dömts",
      studyText: "En person som är misstänkt för ett brott ska betraktas som oskyldig tills personen har dömts för brottet.",
      studyRemember: "Misstänkt betyder inte dömd.",
      section: "Domstolar",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-18",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "easy",
      question: "Vilken domstol är första instans där brottsmål och tvistemål börjar?",
      options: [
        "Tingsrätten",
        "Hovrätten",
        "Högsta domstolen",
        "Åklagarmyndigheten"
      ],
      correctIndex: 0,
      explanationSv: "Tingsrätten är första instans där brottsmål och tvistemål börjar.",
      studyTitle: "Domstolarnas nivåer",
      studyText: "Det finns tre nivåer av domstolar. Tingsrätten är första instans där brottsmål och tvistemål börjar.",
      studyRemember: "Tingsrätten = första instans.",
      section: "Domstolar",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-19",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "medium",
      question: "Vilken domstol prövar fall som har överklagats från tingsrätten?",
      options: [
        "Hovrätten",
        "Högsta domstolen",
        "Riksdagen",
        "Kriminalvården"
      ],
      correctIndex: 0,
      explanationSv: "Hovrätten prövar fall som har överklagats från tingsrätten.",
      studyTitle: "Hovrätten",
      studyText: "Hovrätten prövar fall som har överklagats från tingsrätten.",
      studyRemember: "Tingsrätt → hovrätt.",
      section: "Domstolar",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-20",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "medium",
      question: "Vilka fall prövar Högsta domstolen enligt materialet?",
      options: [
        "Bara vissa viktiga fall som redan gått genom tingsrätt och hovrätt",
        "Alla brottsmål i Sverige",
        "Alla mål direkt efter en polisanmälan",
        "Bara tvister mellan kommuner"
      ],
      correctIndex: 0,
      explanationSv: "Högsta domstolen prövar bara vissa viktiga fall som redan gått igenom tingsrätt och hovrätt.",
      studyTitle: "Högsta domstolen",
      studyText: "Högsta domstolen, HD, prövar bara vissa viktiga fall som redan gått igenom tingsrätt och hovrätt.",
      studyRemember: "HD prövar bara vissa viktiga fall.",
      section: "Domstolar",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-21",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "polisen",
      difficulty: "medium",
      question: "Vilken av dessa uppgifter har Polisen enligt materialet?",
      options: [
        "Att göra pass och nationella id-kort till svenska medborgare",
        "Att stifta Sveriges lagar",
        "Att utse nämndemän",
        "Att bestämma straff i domstol"
      ],
      correctIndex: 0,
      explanationSv: "Polisen gör pass och nationella id-kort till svenska medborgare.",
      studyTitle: "Polisens uppgifter",
      studyText: "Polisen upprätthåller lag och ordning, förebygger och utreder brott, hjälper människor och gör pass och nationella id-kort till svenska medborgare. Polisen beslutar också om vissa tillstånd.",
      studyRemember: "Polisen har fler uppgifter än att utreda brott.",
      section: "Polisen",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-22",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "brottsutredning",
      difficulty: "medium",
      question: "Vad händer under en förundersökning?",
      options: [
        "Polisen samlar bevis och pratar med vittnen",
        "Domstolen bestämmer straffet",
        "Riksdagen ändrar lagen",
        "Kriminalvården avgör om personen är skyldig"
      ],
      correctIndex: 0,
      explanationSv: "Under en förundersökning samlar polisen bevis och pratar med vittnen.",
      studyTitle: "Förundersökning",
      studyText: "I brottsutredningen kommer först polisanmälan och förhör. Under förundersökningen samlar polisen bevis och pratar med vittnen.",
      studyRemember: "Förundersökning = samla bevis och prata med vittnen.",
      section: "Brottsutredning",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-23",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "brottsutredning",
      difficulty: "medium",
      question: "Hur länge kan en misstänkt hållas inlåst efter att en åklagare har anhållit personen?",
      options: [
        "Upp till 72 timmar",
        "Upp till 24 timmar",
        "Upp till 48 timmar",
        "Upp till sju dagar"
      ],
      correctIndex: 0,
      explanationSv: "En misstänkt som har anhållits av en åklagare kan hållas inlåst i upp till 72 timmar.",
      studyTitle: "Anhållan",
      studyText: "Om polisen har starka misstankar mot någon kan personen gripas. En åklagare kan sedan anhålla personen. Den misstänkte kan då hållas inlåst i upp till 72 timmar.",
      studyRemember: "Anhållan: upp till 72 timmar enligt materialet.",
      section: "Brottsutredning",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-24",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "brottsutredning",
      difficulty: "medium",
      question: "Vem beslutar om en misstänkt person ska häktas?",
      options: [
        "En domstol",
        "Polisen",
        "Kommunen",
        "Kriminalvården"
      ],
      correctIndex: 0,
      explanationSv: "Det är en domstol som beslutar om häktning.",
      studyTitle: "Häktning",
      studyText: "Häktning betyder att en domstol beslutar att en misstänkt person ska hållas inlåst under en längre tid.",
      studyRemember: "Domstolen beslutar om häktning.",
      section: "Brottsutredning",
      sourcePage: 18,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-25",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattegang",
      difficulty: "medium",
      question: "Vad försöker åklagaren göra under rättegången?",
      options: [
        "Bevisa att den åtalade är skyldig",
        "Bestämma vem som ska vara domare",
        "Skriva en ny lag",
        "Utse nämndemän"
      ],
      correctIndex: 0,
      explanationSv: "Under rättegången försöker åklagaren bevisa att den åtalade är skyldig.",
      studyTitle: "Rättegången",
      studyText: "Under rättegången försöker åklagaren bevisa att den åtalade är skyldig. Den åtalade har rätt till en försvarsadvokat som kan ifrågasätta åklagarens bevis och lägga fram egna bevis.",
      studyRemember: "Åklagaren försöker bevisa skuld.",
      section: "Rättegång",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-26",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattegang",
      difficulty: "medium",
      question: "Vilken rätt har den åtalade under rättegången?",
      options: [
        "Rätt till en försvarsadvokat",
        "Rätt att själv bestämma domen",
        "Rätt att välja vilka lagar som ska gälla",
        "Rätt att stoppa rättegången"
      ],
      correctIndex: 0,
      explanationSv: "Den åtalade har rätt till en försvarsadvokat.",
      studyTitle: "Försvarsadvokat",
      studyText: "Den åtalade har rätt till en försvarsadvokat som kan ifrågasätta åklagarens bevis och lägga fram egna bevis.",
      studyRemember: "Den åtalade har rätt till en försvarsadvokat.",
      section: "Rättegång",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-27",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "rattegang",
      difficulty: "medium",
      question: "Vilka dömer tillsammans med domaren i tingsrätten?",
      options: [
        "Nämndemän",
        "Poliser",
        "Ministrar",
        "Åklagare"
      ],
      correctIndex: 0,
      explanationSv: "I tingsrätten dömer nämndemän tillsammans med domaren.",
      studyTitle: "Nämndemän",
      studyText: "I tingsrätten dömer nämndemän tillsammans med domaren. De ska representera allmänheten och ge insyn i rättsprocessen. Nämndemännen är utsedda av de politiska partierna.",
      studyRemember: "I tingsrätten dömer nämndemän tillsammans med domaren.",
      section: "Rättegång",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-28",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "straffmyndighet",
      difficulty: "easy",
      question: "Från vilken ålder är en person straffmyndig i Sverige enligt materialet?",
      options: [
        "15 år",
        "13 år",
        "16 år",
        "18 år"
      ],
      correctIndex: 0,
      explanationSv: "Enligt materialet är en person straffmyndig och kan bli åtalad för ett brott från 15 års ålder.",
      studyTitle: "Straffmyndighet",
      studyText: "I Sverige är en person straffmyndig och kan bli åtalad för ett brott från 15 års ålder.",
      studyRemember: "Straffmyndig enligt materialet = från 15 år.",
      section: "Straffmyndighet och belastningsregister",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-29",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "barn_och_brott",
      difficulty: "medium",
      question: "Vem bestämmer vad som ska hända när ett yngre barn gör något brottsligt?",
      options: [
        "Socialtjänsten",
        "Riksdagen",
        "Kriminalvården",
        "Skatteverket"
      ],
      correctIndex: 0,
      explanationSv: "När ett yngre barn gör något brottsligt är det socialtjänsten som bestämmer vad som ska hända med barnet.",
      studyTitle: "Yngre barn och brott",
      studyText: "I Sverige är en person straffmyndig från 15 års ålder. När ett yngre barn gör något brottsligt är det socialtjänsten som bestämmer vad som ska hända med barnet.",
      studyRemember: "Yngre barn: socialtjänsten bestämmer vad som ska hända.",
      section: "Straffmyndighet och belastningsregister",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-30",
      chapter: 5,
      category: "lag_och_ratt",
      topic: "belastningsregister",
      difficulty: "medium",
      question: "Vad kan enligt materialet bli svårare för den som finns i belastningsregistret efter vissa allvarliga brott?",
      options: [
        "Att få jobb, körkort eller medborgarskap",
        "Att rösta i riksdagsval",
        "Att läsa en tidning",
        "Att använda allemansrätten"
      ],
      correctIndex: 0,
      explanationSv: "Materialet säger att ett belastningsregister kan göra det svårare att få jobb, körkort eller medborgarskap.",
      studyTitle: "Belastningsregistret",
      studyText: "Den som döms för vissa allvarliga brott registreras i ett belastningsregister. Det kan göra det svårare att få jobb, körkort eller medborgarskap.",
      studyRemember: "Belastningsregister kan påverka jobb, körkort och medborgarskap.",
      section: "Straffmyndighet och belastningsregister",
      sourcePage: 19,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    }
  ];

  window.SVERIGEQUIZ_QUESTIONS.push(...chapterQuestions);
})();
