// Sverigequiz – kapitel 1–3, produktionspaket 2026-09-21
// Laddas EFTER questions.js och FÖRE app.js.
// Ersätter befintliga frågor från kapitel 1–3 med kvalitetssäkrade versioner
// och lägger till nya frågor. Övriga frågor lämnas orörda.

(() => {
  const replacementIds = [
    "q0006", "q0007", "q0011", "q0012", "q0013", "q0014",
    "q0015", "q0016", "q0017", "q0033", "q0036", "q0037",
    "q0038", "q0039", "q0040", "q0041", "q0042", "q0043",
    "q0044", "q0045", "q0046", "q0047",
    "q0002", "q0003", "q0032", "q0048", "q0049", "q0050",
    "q0051", "q0052", "q0053", "q0054", "q0055", "q0056"
  ];

  const replacementChapters = new Set([1, 2, 3]);

  window.SVERIGEQUIZ_QUESTIONS = window.SVERIGEQUIZ_QUESTIONS.filter(q =>
    !replacementChapters.has(q.chapter) && !replacementIds.includes(q.id)
  );

  const chapterQuestions = [
    {
      id: "q0006",
      chapter: 1,
      category: "landet_sverige",
      topic: "sveriges_indelning",
      difficulty: "easy",
      question: "Vilka är Sveriges tre stora landsdelar?",
      options: [
        "Götaland, Svealand och Norrland",
        "Stockholm, Göteborg och Malmö",
        "Norrbotten, Västerbotten och Lappland",
        "Öland, Gotland och Svealand"
      ],
      correctIndex: 0,
      explanationSv: "Sverige delas in i Götaland, Svealand och Norrland.",
      studyTitle: "Sveriges landsdelar",
      studyText: "Sverige brukar delas in i tre stora landsdelar. Götaland ligger i söder, Svealand i mellersta Sverige och Norrland i norr. Norrland omfattar mer än hälften av Sveriges yta.",
      studyRemember: "Götaland – Svealand – Norrland.",
      section: "Sveriges indelning",
      sourcePage: 6,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0007",
      chapter: 1,
      category: "landet_sverige",
      topic: "natur",
      difficulty: "easy",
      question: "Vilka är Sveriges tre största sjöar?",
      options: [
        "Vänern, Vättern och Mälaren",
        "Mälaren, Hjälmaren och Siljan",
        "Vättern, Siljan och Storsjön",
        "Vänern, Hjälmaren och Torneträsk"
      ],
      correctIndex: 0,
      explanationSv: "De tre största sjöarna är Vänern, Vättern och Mälaren.",
      studyTitle: "Sjöar i Sverige",
      studyText: "Sverige har många sjöar. De tre största är Vänern, Vättern och Mälaren. Det finns också många åar och älvar, och de största älvarna rinner från fjällen mot havet.",
      studyRemember: "De tre största: Vänern, Vättern och Mälaren.",
      section: "Skogar, sjöar och öar",
      sourcePage: 6,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0011",
      chapter: 1,
      category: "landet_sverige",
      topic: "norden",
      difficulty: "easy",
      question: "Vilket är det största landet i Norden?",
      options: ["Sverige", "Danmark", "Island", "Finland"],
      correctIndex: 0,
      explanationSv: "Sverige är det största landet i Norden.",
      studyTitle: "Sverige i Norden",
      studyText: "Norden ligger i norra Europa och består av Danmark, Finland, Island, Norge och Sverige. Sverige är det största landet i Norden.",
      studyRemember: "Sverige är störst i Norden.",
      section: "Geografi, klimat och natur",
      sourcePage: 5,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0012",
      chapter: 1,
      category: "landet_sverige",
      topic: "geografi",
      difficulty: "easy",
      question: "Vilket hav ligger längs Sveriges östra kust?",
      options: ["Östersjön", "Nordsjön", "Medelhavet", "Norska havet"],
      correctIndex: 0,
      explanationSv: "Havet vid Sveriges östra kust heter Östersjön.",
      studyTitle: "Sveriges kust",
      studyText: "Sverige har en lång kust. Vid östkusten ligger Östersjön. Vid västkusten ligger Skagerrak och Kattegatt.",
      studyRemember: "Östkusten = Östersjön.",
      section: "Geografi, klimat och natur",
      sourcePage: 5,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0013",
      chapter: 1,
      category: "landet_sverige",
      topic: "geografi",
      difficulty: "easy",
      question: "Vilka är Sveriges två största öar?",
      options: [
        "Gotland och Öland",
        "Öland och Orust",
        "Gotland och Hisingen",
        "Tjörn och Orust"
      ],
      correctIndex: 0,
      explanationSv: "Sveriges två största öar är Gotland och Öland.",
      studyTitle: "Sveriges största öar",
      studyText: "Sveriges två största öar är Gotland och Öland. De ligger i Östersjön.",
      studyRemember: "Gotland och Öland är störst.",
      section: "Geografi, klimat och natur",
      sourcePage: 5,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0014",
      chapter: 1,
      category: "landet_sverige",
      topic: "natur",
      difficulty: "easy",
      question: "Vad heter Sveriges högsta berg?",
      options: ["Kebnekaise", "Åreskutan", "Kinnekulle", "Omberg"],
      correctIndex: 0,
      explanationSv: "Sveriges högsta berg är Kebnekaise.",
      studyTitle: "Fjällen",
      studyText: "Skanderna ligger längs gränsen mot Norge och kallas fjällen. Där finns Sveriges högsta berg Kebnekaise, som är cirka 2 000 meter högt.",
      studyRemember: "Kebnekaise är Sveriges högsta berg.",
      section: "Fjäll",
      sourcePage: 6,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0015",
      chapter: 1,
      category: "landet_sverige",
      topic: "sveriges_indelning",
      difficulty: "medium",
      question: "Hur många kommuner är Sverige indelat i?",
      options: ["290", "21", "25", "349"],
      correctIndex: 0,
      explanationSv: "Sverige är indelat i 290 kommuner.",
      studyTitle: "Län, landskap och kommuner",
      studyText: "Sverige har 25 landskap, 21 län och 290 kommuner. Landskapen har i dag ingen betydelse för hur Sverige styrs.",
      studyRemember: "290 kommuner – 21 län – 25 landskap.",
      section: "Sveriges indelning",
      sourcePage: 6,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0016",
      chapter: 1,
      category: "landet_sverige",
      topic: "befolkning",
      difficulty: "medium",
      question: "Ungefär hur stor del av Sveriges befolkning bor i städer?",
      options: ["85 procent", "25 procent", "50 procent", "100 procent"],
      correctIndex: 0,
      explanationSv: "Ungefär 85 procent av Sveriges befolkning bor i städer.",
      studyTitle: "Befolkningen",
      studyText: "I Sverige bor nästan 11 miljoner människor. De flesta bor i södra Sverige och längs kusterna. Ungefär 85 procent av befolkningen bor i städer.",
      studyRemember: "Cirka 85 procent bor i städer.",
      section: "Befolkning",
      sourcePage: 7,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0017",
      chapter: 1,
      category: "landet_sverige",
      topic: "klimat",
      difficulty: "medium",
      question: "Vilket år är målet att Sveriges utsläpp av växthusgaser ska vara så nära noll som möjligt?",
      options: ["2045", "2030", "2055", "2100"],
      correctIndex: 0,
      explanationSv: "Ett klimatpolitiskt mål är att utsläppen ska vara så nära noll som möjligt år 2045.",
      studyTitle: "Sveriges klimatarbete",
      studyText: "Sverige arbetar för att minska utsläppen av växthusgaser. Ett klimatpolitiskt mål är att utsläppen ska vara så nära noll som möjligt år 2045.",
      studyRemember: "Klimatmålet: nära noll år 2045.",
      section: "Sveriges arbete för att minska klimathoten",
      sourcePage: 9,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0033",
      chapter: 1,
      category: "landet_sverige",
      topic: "naturresurser",
      difficulty: "easy",
      question: "Vilken svensk naturresurs har under lång tid haft stor betydelse för Sveriges ekonomi?",
      options: ["Naturgas", "Olja", "Skog", "Uran"],
      correctIndex: 2,
      explanationSv: "Skogen är en svensk naturresurs som under lång tid har haft stor betydelse för ekonomin.",
      studyTitle: "Skogen som naturresurs",
      studyText: "Mer än hälften av Sveriges yta täcks av skog. Skogsprodukter säljs till många länder och skogsindustrin är en av Sveriges viktigaste näringar.",
      studyRemember: "Skogen är en viktig svensk naturresurs.",
      section: "Skog",
      sourcePage: 8,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0036",
      chapter: 1,
      category: "landet_sverige",
      topic: "klimat",
      difficulty: "medium",
      question: "Varför har Sverige ett relativt milt klimat trots sitt nordliga läge?",
      options: [
        "Golfströmmen och den Nordatlantiska strömmen för varmt vatten mot Europa",
        "Sverige ligger söder om ekvatorn",
        "Fjällen värmer upp hela landet",
        "Östersjön är alltid varm"
      ],
      correctIndex: 0,
      explanationSv: "Varma havsströmmar bidrar till att Sverige har ett mildare klimat än många andra områden på samma breddgrad.",
      studyTitle: "Varma havsströmmar",
      studyText: "Golfströmmen och den Nordatlantiska strömmen transporterar varmt vatten över Atlanten mot Europa. Det hjälper till att ge Sverige ett mildare och fuktigare klimat.",
      studyRemember: "Varma havsströmmar gör klimatet mildare.",
      section: "Geografi, klimat och natur",
      sourcePage: 5,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0037",
      chapter: 1,
      category: "landet_sverige",
      topic: "naturresurser",
      difficulty: "medium",
      question: "Hur används rinnande vatten som en viktig energikälla i Sverige?",
      options: [
        "I vattenkraftverk för att producera el",
        "För att tillverka bensin",
        "För att värma kärnkraftverk med ved",
        "För att skapa naturgas"
      ],
      correctIndex: 0,
      explanationSv: "I vattenkraftverk används rinnande vatten för att producera el.",
      studyTitle: "Vatten som naturresurs",
      studyText: "Sverige har gott om sjöar, vattendrag och älvar. I flera älvar finns vattenkraftverk där rinnande vatten används för att producera el. Vattenkraft står för en stor del av Sveriges elproduktion.",
      studyRemember: "Vattenkraft = rinnande vatten blir el.",
      section: "Vatten",
      sourcePage: 8,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },

    // KAPITEL 2 – SVERIGES DEMOKRATISKA SYSTEM

    {
      id: "q0038",
      chapter: 2,
      category: "demokrati",
      topic: "folkstyre",
      difficulty: "easy",
      question: "Vad betyder ordet demokrati?",
      options: ["Folkstyre", "Kungastyre", "Militärstyre", "Enpartistyre"],
      correctIndex: 0,
      explanationSv: "Demokrati betyder folkstyre – makten utgår från folket.",
      studyTitle: "Demokrati",
      studyText: "Demokrati är ett politiskt system där makten utgår från folket. Medborgarna ska kunna påverka beslut och välja mellan olika politiska alternativ. De som får makten ska kunna bytas ut.",
      studyRemember: "Demokrati = folkstyre.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0039",
      chapter: 2,
      category: "demokrati",
      topic: "fria_val",
      difficulty: "easy",
      question: "Vad kännetecknar ett fritt val?",
      options: [
        "De röstberättigade kan rösta utan hot eller tvång",
        "Alla måste rösta på samma parti",
        "Regeringen bestämmer hur varje person ska rösta",
        "Bara politiker får rösta"
      ],
      correctIndex: 0,
      explanationSv: "I fria val ska de som har rösträtt kunna uttrycka sin vilja utan hot eller tvång.",
      studyTitle: "Fria val",
      studyText: "I en demokrati har människor rätt att rösta i fria val. Alla som har rösträtt har en röst var och ska kunna rösta utan hot eller tvång. Det ska finnas flera politiska alternativ.",
      studyRemember: "Fria val = en röst var, utan hot eller tvång.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0040",
      chapter: 2,
      category: "demokrati",
      topic: "hemliga_val",
      difficulty: "easy",
      question: "Vad betyder det att ett val är hemligt?",
      options: [
        "Ingen behöver avslöja hur han eller hon röstar",
        "Valresultatet får aldrig offentliggöras",
        "Bara valmyndigheten får rösta",
        "Man får inte prata om politik före valet"
      ],
      correctIndex: 0,
      explanationSv: "Hemliga val betyder att ingen behöver avslöja hur han eller hon röstar.",
      studyTitle: "Hemliga val",
      studyText: "Valen ska vara hemliga. Det betyder att du själv bestämmer om du vill berätta hur du röstar. Ingen ska kunna kräva att få veta vilket parti du väljer.",
      studyRemember: "Hemligt val = du behöver inte avslöja din röst.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0041",
      chapter: 2,
      category: "demokrati",
      topic: "yttrandefrihet",
      difficulty: "easy",
      question: "Vad innebär yttrandefrihet i en demokrati?",
      options: [
        "Rätt att skriva och säga vad man tycker",
        "Rätt att bestämma över domstolar",
        "Rätt att slippa följa lagar",
        "Rätt att hindra andra från att tala"
      ],
      correctIndex: 0,
      explanationSv: "Yttrandefrihet innebär att människor har rätt att skriva och säga vad de tycker.",
      studyTitle: "Yttrandefrihet",
      studyText: "I en demokrati får människor, grupper och partier försöka övertyga andra om sina idéer. Yttrandefrihet innebär rätten att skriva och säga vad man tycker.",
      studyRemember: "Yttrandefrihet = rätt att uttrycka sina åsikter.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0042",
      chapter: 2,
      category: "demokrati",
      topic: "rattssakerhet",
      difficulty: "medium",
      question: "Vad är en viktig del av rättssäkerheten?",
      options: [
        "Ingen får dömas utan en rättvis rättegång",
        "Politiker får döma personer utan domstol",
        "Olika lagar gäller för olika människor",
        "Den som är misstänkt är alltid skyldig"
      ],
      correctIndex: 0,
      explanationSv: "Rättssäkerhet innebär bland annat att lagarna gäller alla och att ingen får dömas utan en rättvis rättegång.",
      studyTitle: "Rättssäkerhet",
      studyText: "En viktig förutsättning för demokrati är att lagarna gäller för alla. Ingen får dömas utan en rättvis rättegång. Det är en del av rättssäkerheten.",
      studyRemember: "Rättssäkerhet = lagen gäller alla och rättegången ska vara rättvis.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0043",
      chapter: 2,
      category: "demokrati",
      topic: "deltagande",
      difficulty: "medium",
      question: "Vilket är ett demokratiskt sätt att påverka samhället mellan valen?",
      options: [
        "Kontakta politiker eller delta i en förening",
        "Hota en journalist",
        "Förbjuda andra åsikter",
        "Sprida falsk information"
      ],
      correctIndex: 0,
      explanationSv: "Man kan påverka på många demokratiska sätt, till exempel genom föreningar, kontakt med politiker och demonstrationer.",
      studyTitle: "Påverka samhället",
      studyText: "Demokrati handlar inte bara om att rösta. Man kan också gå med i ett parti eller en förening, kontakta politiker, demonstrera, skriva på namninsamlingar eller lämna synpunkter till kommunen.",
      studyRemember: "Du kan påverka även mellan valen.",
      section: "Demokrati betyder folkstyre",
      sourcePage: 10,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0044",
      chapter: 2,
      category: "demokrati",
      topic: "hot_mot_demokratin",
      difficulty: "medium",
      question: "Varför kan ett lågt valdeltagande vara ett problem för demokratin?",
      options: [
        "Färre människor är med och påverkar de politiska besluten",
        "Riksdagen får fler ledamöter",
        "Valen blir automatiskt ogiltiga",
        "Kommunerna slutar att finnas"
      ],
      correctIndex: 0,
      explanationSv: "Ett lågt valdeltagande kan göra att färre människor är med och påverkar och kan öka skillnader mellan grupper.",
      studyTitle: "Lågt valdeltagande",
      studyText: "Demokratin fungerar bättre när många kan vara med och påverka. Ett lågt valdeltagande kan bero på bristande tillit eller känslan att den egna rösten inte spelar någon roll.",
      studyRemember: "Många som deltar stärker demokratin.",
      section: "Hot mot demokratin",
      sourcePage: 11,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0045",
      chapter: 2,
      category: "demokrati",
      topic: "hot_mot_demokratin",
      difficulty: "medium",
      question: "Vilket exempel beskriver ett hot mot den demokratiska debatten?",
      options: [
        "En journalist hotas för att hon skriver om samhällsfrågor",
        "Två partier diskuterar olika förslag",
        "En väljare byter parti mellan två val",
        "En förening ordnar ett öppet möte"
      ],
      correctIndex: 0,
      explanationSv: "Hot mot politiker, journalister och andra debattörer kan skrämma människor från att delta i samhällsdebatten.",
      studyTitle: "Skydda den demokratiska debatten",
      studyText: "Falsk information och hat kan skapa konflikter. Hot mot politiker, journalister och andra som deltar i samhällsdebatten kan göra att människor blir rädda för att uttrycka sig.",
      studyRemember: "Hot och falsk information kan försvaga demokratin.",
      section: "Hot mot demokratin",
      sourcePage: 11,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0046",
      chapter: 2,
      category: "demokrati",
      topic: "segregation",
      difficulty: "medium",
      question: "Vad betyder segregation i samhället?",
      options: [
        "Att människor lever åtskilda beroende på till exempel ekonomi eller etnisk bakgrund",
        "Att alla människor röstar på samma parti",
        "Att stat och kommun slås ihop",
        "Att människor med olika bakgrund känner större delaktighet"
      ],
      correctIndex: 0,
      explanationSv: "Segregation innebär bland annat att människor lever åtskilda beroende på ekonomi eller etnisk bakgrund.",
      studyTitle: "Segregation",
      studyText: "Segregation betyder att grupper i samhället lever mer åtskilda, till exempel beroende på ekonomi eller etnisk bakgrund. Det kan ge olika tillgång till service och minska kontakten mellan grupper.",
      studyRemember: "Segregation = människor lever mer åtskilda.",
      section: "Segregation och integration",
      sourcePage: 11,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0047",
      chapter: 2,
      category: "demokrati",
      topic: "integration",
      difficulty: "medium",
      question: "Vad beskriver integration bäst?",
      options: [
        "Människor med olika bakgrund lever närmare varandra och känner delaktighet",
        "Människor delas upp efter inkomst och bakgrund",
        "Alla måste ha samma åsikter",
        "Bara staten får delta i samhällsdebatten"
      ],
      correctIndex: 0,
      explanationSv: "Integration innebär att människor med olika bakgrund och ekonomi lever närmare varandra och känner sig delaktiga i samhället.",
      studyTitle: "Integration",
      studyText: "Integration handlar om att människor med olika bakgrund och ekonomi lever närmare varandra och känner delaktighet. Språkutbildning och blandade bostadsområden är exempel på åtgärder som kan underlätta integration.",
      studyRemember: "Integration = närhet och delaktighet.",
      section: "Segregation och integration",
      sourcePage: 11,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },

    // KAPITEL 3 – SÅ HÄR STYRS SVERIGE

    {
      id: "q0002",
      chapter: 3,
      category: "styrning",
      topic: "riksdagen",
      difficulty: "easy",
      question: "Vem beslutar om Sveriges lagar och statens budget?",
      options: ["Riksdagen", "Kungen", "Polisen", "Kommunerna"],
      correctIndex: 0,
      explanationSv: "Riksdagen beslutar om lagar och om hur statens pengar ska användas.",
      studyTitle: "Riksdagen",
      studyText: "Medborgarna väljer riksdagens ledamöter i allmänna val. Riksdagen beslutar om Sveriges lagar och statens budget.",
      studyRemember: "Riksdagen beslutar om lagar och statens budget.",
      section: "Staten",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0003",
      chapter: 3,
      category: "styrning",
      topic: "regioner",
      difficulty: "easy",
      question: "Vilket område ansvarar regionerna främst för?",
      options: ["Hälso- och sjukvård", "Grundskolor", "Polisen", "Försvaret"],
      correctIndex: 0,
      explanationSv: "Regionernas främsta uppgift är att ansvara för hälso- och sjukvården.",
      studyTitle: "Regionernas ansvar",
      studyText: "Sverige har 21 regioner. Deras främsta uppgift är hälso- och sjukvård. Regionerna ansvarar också för bland annat kollektivtrafik och länsmuseer.",
      studyRemember: "Regionerna ansvarar främst för hälso- och sjukvård.",
      section: "Regioner och kommuner",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0032",
      chapter: 3,
      category: "styrning",
      topic: "statsskick",
      difficulty: "easy",
      question: "Vilken titel har Sveriges statschef?",
      options: ["Talman", "Kung", "Landshövding", "Statsminister"],
      correctIndex: 1,
      explanationSv: "Sveriges statschef är kungen.",
      studyTitle: "Sveriges statschef",
      studyText: "Sverige är en konstitutionell monarki. Statschefen är en kung eller drottning och har ingen politisk makt. Kungen fungerar som en symbol för Sverige.",
      studyRemember: "Statschefen är kungen och har ingen politisk makt.",
      section: "Sveriges statsskick",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0048",
      chapter: 3,
      category: "styrning",
      topic: "styrelsenivaer",
      difficulty: "easy",
      question: "På vilka tre politiska nivåer delas ansvaret i Sverige?",
      options: [
        "Stat, region och kommun",
        "Riksdag, polis och domstol",
        "Landskap, socken och by",
        "Kung, regering och EU"
      ],
      correctIndex: 0,
      explanationSv: "Det politiska ansvaret delas mellan staten, regionerna och kommunerna.",
      studyTitle: "Tre politiska nivåer",
      studyText: "Sverige styrs på nationell, regional och kommunal nivå. Det betyder stat, regioner och kommuner. Sverige påverkas dessutom av beslut i EU.",
      studyRemember: "Stat – region – kommun.",
      section: "Landet styrs på olika nivåer",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0049",
      chapter: 3,
      category: "styrning",
      topic: "riksdagen",
      difficulty: "medium",
      question: "Hur många ledamöter har Sveriges riksdag?",
      options: ["349", "290", "21", "100"],
      correctIndex: 0,
      explanationSv: "Riksdagen har 349 ledamöter som väljs vart fjärde år.",
      studyTitle: "Riksdagen",
      studyText: "Riksdagen har 349 ledamöter. De väljs vart fjärde år och representerar olika partier och delar av landet.",
      studyRemember: "Riksdagen har 349 ledamöter.",
      section: "Staten",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0050",
      chapter: 3,
      category: "styrning",
      topic: "regeringen",
      difficulty: "medium",
      question: "Vem väljer statsministern i Sverige?",
      options: ["Riksdagen", "Kungen", "Högsta domstolen", "Regionerna"],
      correctIndex: 0,
      explanationSv: "Riksdagen väljer statsminister, som sedan väljer ministrarna i regeringen.",
      studyTitle: "Statsminister och regering",
      studyText: "Riksdagen väljer statsminister. Statsministern får i uppdrag att bilda regering och väljer därefter ministrarna.",
      studyRemember: "Riksdagen väljer statsminister; statsministern väljer ministrarna.",
      section: "Staten",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0051",
      chapter: 3,
      category: "styrning",
      topic: "budget",
      difficulty: "medium",
      question: "Vad är en budgetproposition?",
      options: [
        "Regeringens förslag till riksdagen om statens inkomster och utgifter",
        "Kommunens plan för skolornas läroplan",
        "Kungens förslag till nya lagar",
        "Domstolarnas årsrapport"
      ],
      correctIndex: 0,
      explanationSv: "Budgetpropositionen är regeringens förslag till riksdagen om statens inkomster och utgifter.",
      studyTitle: "Budgetpropositionen",
      studyText: "Varje höst lämnar regeringen ett förslag till riksdagen om statens inkomster och utgifter. Det kallas budgetproposition och visar regeringens prioriteringar.",
      studyRemember: "Budgetproposition = regeringens förslag till statens budget.",
      section: "Staten",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0052",
      chapter: 3,
      category: "styrning",
      topic: "opposition",
      difficulty: "medium",
      question: "Vad är en viktig uppgift för oppositionen i riksdagen?",
      options: [
        "Att granska regeringen och föreslå en annan politik",
        "Att utse alla domare",
        "Att leda Försvarsmakten",
        "Att bestämma kommunernas alla beslut"
      ],
      correctIndex: 0,
      explanationSv: "Oppositionen granskar regeringens arbete och kan föreslå en annan politik.",
      studyTitle: "Oppositionen",
      studyText: "De partier som inte stödjer regeringen kallas opposition. Oppositionen granskar regeringens arbete och föreslår alternativ.",
      studyRemember: "Oppositionen granskar regeringen.",
      section: "Staten",
      sourcePage: 12,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0053",
      chapter: 3,
      category: "styrning",
      topic: "myndigheter",
      difficulty: "medium",
      question: "Vilken myndighet fattar beslut om föräldrapenning?",
      options: ["Försäkringskassan", "Migrationsverket", "Polismyndigheten", "Skatteverket"],
      correctIndex: 0,
      explanationSv: "Försäkringskassan fattar beslut om bland annat föräldrapenning.",
      studyTitle: "Statliga myndigheter",
      studyText: "Regeringen styr landet med hjälp av statliga myndigheter. Försäkringskassan är ett exempel och fattar bland annat beslut om föräldrapenning.",
      studyRemember: "Föräldrapenning → Försäkringskassan.",
      section: "Myndigheter",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0054",
      chapter: 3,
      category: "styrning",
      topic: "myndigheter",
      difficulty: "medium",
      question: "Vad måste statliga myndigheter följa?",
      options: [
        "Lagen och regeringens instruktioner",
        "Kungens privata önskemål",
        "Beslut från vilket företag som helst",
        "Endast kommunens regler"
      ],
      correctIndex: 0,
      explanationSv: "Myndigheterna måste följa lagen och de instruktioner de har fått av regeringen.",
      studyTitle: "Myndigheternas arbete",
      studyText: "Statliga myndigheter genomför beslut i praktiken. De måste följa lagen och regeringens instruktioner. JO och JK är exempel på myndigheter som kontrollerar att andra myndigheter gör rätt.",
      studyRemember: "Myndigheter måste följa lagen.",
      section: "Myndigheter",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0055",
      chapter: 3,
      category: "styrning",
      topic: "kommuner",
      difficulty: "medium",
      question: "Vilket av följande är ett kommunalt ansvar?",
      options: [
        "Vatten och avlopp",
        "Sveriges försvar",
        "Att stifta Sveriges lagar",
        "Att besluta om föräldrapenning"
      ],
      correctIndex: 0,
      explanationSv: "Kommunerna ansvarar bland annat för vatten och avlopp, äldreomsorg, barnomsorg, snöröjning och vuxenutbildning.",
      studyTitle: "Kommunernas ansvar",
      studyText: "Kommunerna ansvarar för mycket service nära invånarna, till exempel vatten och avlopp, omsorg för äldre och barn, snöröjning, parkskötsel och utbildning för vuxna.",
      studyRemember: "Kommunen sköter mycket av vardagens lokala service.",
      section: "Regioner och kommuner",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "q0056",
      chapter: 3,
      category: "styrning",
      topic: "statsskick",
      difficulty: "medium",
      question: "Vad betyder det att Sverige är en konstitutionell monarki?",
      options: [
        "Statschefen är kung eller drottning men har ingen politisk makt",
        "Kungen bestämmer vilka lagar riksdagen ska anta",
        "Statsministern ärver sitt ämbete",
        "Militären utser regeringen"
      ],
      correctIndex: 0,
      explanationSv: "I en konstitutionell monarki är statschefen kung eller drottning utan politisk makt.",
      studyTitle: "Konstitutionell monarki",
      studyText: "Sverige är en konstitutionell monarki. Kungen är statschef och symbol för Sverige, men har ingen politisk makt.",
      studyRemember: "Konstitutionell monarki = monark som statschef utan politisk makt.",
      section: "Sveriges statsskick",
      sourcePage: 13,
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    }
  ];

  window.SVERIGEQUIZ_QUESTIONS.push(...chapterQuestions);
})();
