// Sverigequiz – kapitel 5
// Lag och rätt
// Källa: Sverige i fokus 2026-1, korrigerad 2026-08-10

(() => {
  const chapter5Questions = [
    {
      id: "ch5-001",
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "easy",
      question: "Hur många grundlagar har Sverige?",
      options: ["Två", "Tre", "Fyra", "Fem"],
      correctIndex: 2,
      explanationSv: "Sverige har fyra grundlagar.",
      chapter: 5,
      section: "Grundlagarna",
      sourcePage: 16,
      studyText: "Sverige har fyra grundlagar: regeringsformen, tryckfrihetsförordningen, yttrandefrihetsgrundlagen och successionsordningen.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-002",
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "easy",
      question: "Vilken av dessa är en av Sveriges grundlagar?",
      options: ["Regeringsformen", "Kommunallagen", "Skollagen", "Trafiklagen"],
      correctIndex: 0,
      explanationSv: "Regeringsformen är en av Sveriges fyra grundlagar.",
      chapter: 5,
      section: "Grundlagarna",
      sourcePage: 16,
      studyText: "Sverige har fyra grundlagar. Regeringsformen är en av dem.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-003",
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "medium",
      question: "Vad säger regeringsformen om den offentliga makten i Sverige?",
      options: [
        "Den utgår från regeringen",
        "Den utgår från kungen",
        "Den utgår från folket",
        "Den utgår från domstolarna"
      ],
      correctIndex: 2,
      explanationSv: "Regeringsformen säger att all offentlig makt i Sverige utgår från folket.",
      chapter: 5,
      section: "Regeringsformen",
      sourcePage: 16,
      studyText: "Regeringsformen säger att all offentlig makt utgår från folket, att riksdagen stiftar lagar och att regeringen styr landet.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-004",
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "easy",
      question: "Vad skyddar tryckfrihetsförordningen?",
      options: [
        "Det fria ordet i tryckt form",
        "Rätten till sjukvård",
        "Rätten till semester",
        "Rätten att rösta"
      ],
      correctIndex: 0,
      explanationSv: "Tryckfrihetsförordningen skyddar det fria ordet i tryckt form.",
      chapter: 5,
      section: "Tryckfrihetsförordningen",
      sourcePage: 16,
      studyText: "Tryckfrihetsförordningen skyddar det fria ordet i tryckt form och ger alla rätt att fritt ge ut böcker, tidningar och tidskrifter.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-005",
      category: "lag_och_ratt",
      topic: "grundlagar",
      difficulty: "easy",
      question: "Vad bestämmer successionsordningen?",
      options: [
        "Hur riksdagen väljs",
        "Vem som ska bli kung eller drottning efter den nuvarande",
        "Hur kommunerna styrs",
        "Vilka brott som ger fängelse"
      ],
      correctIndex: 1,
      explanationSv: "Successionsordningen bestämmer vem som ska bli kung eller drottning efter den nuvarande.",
      chapter: 5,
      section: "Successionsordningen",
      sourcePage: 16,
      studyText: "Successionsordningen är den grundlag som bestämmer vem som ska bli kung eller drottning efter den nuvarande.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-006",
      category: "lag_och_ratt",
      topic: "allemansratt",
      difficulty: "easy",
      question: "I vilken grundlag skyddas allemansrätten?",
      options: [
        "Regeringsformen",
        "Successionsordningen",
        "Tryckfrihetsförordningen",
        "Yttrandefrihetsgrundlagen"
      ],
      correctIndex: 0,
      explanationSv: "Allemansrätten skyddas i regeringsformen.",
      chapter: 5,
      section: "Allemansrätten är skyddad i grundlagen",
      sourcePage: 17,
      studyText: "Den svenska allemansrätten skyddas i regeringsformen och ger alla möjlighet att vara i naturen oavsett vem som äger marken.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-007",
      category: "lag_och_ratt",
      topic: "allemansratt",
      difficulty: "medium",
      question: "Vad måste man tänka på när man använder allemansrätten?",
      options: [
        "Att alltid fråga kommunen",
        "Att inte skada naturen eller störa markägaren",
        "Att bara vara i statlig skog",
        "Att aldrig sätta upp tält"
      ],
      correctIndex: 1,
      explanationSv: "Man ska vara ansvarsfull och inte skada naturen eller störa markägaren.",
      chapter: 5,
      section: "Allemansrätten är skyddad i grundlagen",
      sourcePage: 17,
      studyText: "Allemansrätten ger stora möjligheter att vara i naturen, men man ska vara ansvarsfull och inte skada naturen eller störa markägaren.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-008",
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "easy",
      question: "Vilken myndighet förhindrar, utreder och bekämpar brott?",
      options: ["Polisen", "Riksdagen", "Skatteverket", "Kommunen"],
      correctIndex: 0,
      explanationSv: "Polisen förhindrar, utreder och bekämpar brott.",
      chapter: 5,
      section: "Rättsväsendet",
      sourcePage: 17,
      studyText: "Polisen är en del av rättsväsendet och arbetar med att förhindra, utreda och bekämpa brott.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-009",
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "medium",
      question: "Vilken myndighet avgör om en person som misstänks för brott ska ställas inför domstol?",
      options: [
        "Kriminalvården",
        "Åklagarmyndigheten",
        "Brottsoffermyndigheten",
        "Kommunen"
      ],
      correctIndex: 1,
      explanationSv: "Åklagarmyndigheten avgör om en person som misstänks för brott ska ställas inför domstol.",
      chapter: 5,
      section: "Rättsväsendet",
      sourcePage: 17,
      studyText: "Åklagarmyndigheten avgör om personer som misstänks för brott ska ställas inför en domstol.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-010",
      category: "lag_och_ratt",
      topic: "rattsvasende",
      difficulty: "medium",
      question: "Vad ansvarar Kriminalvården bland annat för?",
      options: [
        "Riksdagsval",
        "Fängelser och att dömda personer avtjänar sina straff",
        "Att skriva nya lagar",
        "Att utfärda pass"
      ],
      correctIndex: 1,
      explanationSv: "Kriminalvården ansvarar bland annat för fängelser och för att dömda personer avtjänar sina straff.",
      chapter: 5,
      section: "Rättsväsendet",
      sourcePage: 17,
      studyText: "Kriminalvården ansvarar bland annat för fängelser och för att dömda personer avtjänar sina straff.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-011",
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "easy",
      question: "Vilken domstol är första instans för brottsmål och tvistemål?",
      options: ["Hovrätten", "Tingsrätten", "Högsta domstolen", "Riksdagen"],
      correctIndex: 1,
      explanationSv: "Tingsrätten är första instans, där brottsmål och tvistemål börjar.",
      chapter: 5,
      section: "Domstolar",
      sourcePage: 18,
      studyText: "Det finns tre nivåer av domstolar. Tingsrätten är första instans, där brottsmål och tvistemål börjar.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-012",
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "medium",
      question: "Vilken domstol prövar fall som har överklagats från tingsrätten?",
      options: ["Hovrätten", "Kommunfullmäktige", "Högsta domstolen direkt", "Åklagarmyndigheten"],
      correctIndex: 0,
      explanationSv: "Hovrätten prövar fall som har överklagats från tingsrätten.",
      chapter: 5,
      section: "Domstolar",
      sourcePage: 18,
      studyText: "Tingsrätten är första instans. Hovrätten prövar fall som har överklagats från tingsrätten.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-013",
      category: "lag_och_ratt",
      topic: "domstolar",
      difficulty: "medium",
      question: "Hur ska en person som misstänks för brott betraktas innan personen har dömts?",
      options: ["Som skyldig", "Som oskyldig", "Som dömd", "Som vittne"],
      correctIndex: 1,
      explanationSv: "En misstänkt person ska betraktas som oskyldig tills personen har dömts för brottet.",
      chapter: 5,
      section: "Domstolar",
      sourcePage: 18,
      studyText: "En person som är misstänkt för ett brott ska betraktas som oskyldig tills personen har dömts för brottet.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-014",
      category: "lag_och_ratt",
      topic: "polis_brottsutredning",
      difficulty: "medium",
      question: "Vad händer under en förundersökning?",
      options: [
        "Polisen samlar bevis och pratar med vittnen",
        "Riksdagen ändrar lagen",
        "Domaren bestämmer straffet",
        "Kriminalvården bestämmer om personen är skyldig"
      ],
      correctIndex: 0,
      explanationSv: "Under förundersökningen samlar polisen bevis och pratar med vittnen.",
      chapter: 5,
      section: "Brottsutredning",
      sourcePage: 18,
      studyText: "Vid en förundersökning samlar polisen bevis och pratar med vittnen.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-015",
      category: "lag_och_ratt",
      topic: "polis_brottsutredning",
      difficulty: "medium",
      question: "Hur länge kan en misstänkt hållas inlåst efter att en åklagare har anhållit personen?",
      options: ["Upp till 24 timmar", "Upp till 48 timmar", "Upp till 72 timmar", "Upp till 7 dagar"],
      correctIndex: 2,
      explanationSv: "En anhållen person kan hållas inlåst i upp till 72 timmar.",
      chapter: 5,
      section: "Brottsutredning",
      sourcePage: 18,
      studyText: "En åklagare kan anhålla en misstänkt person. Den misstänkte kan då hållas inlåst i upp till 72 timmar.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-016",
      category: "lag_och_ratt",
      topic: "polis_brottsutredning",
      difficulty: "medium",
      question: "Vem beslutar att en misstänkt person ska häktas?",
      options: ["Polisen", "En domstol", "Kommunen", "Kriminalvården"],
      correctIndex: 1,
      explanationSv: "Det är en domstol som beslutar om häktning.",
      chapter: 5,
      section: "Brottsutredning",
      sourcePage: 18,
      studyText: "Häktning betyder att en domstol beslutar att en misstänkt person ska hållas inlåst under en längre tid.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-017",
      category: "lag_och_ratt",
      topic: "rattegang_straff",
      difficulty: "medium",
      question: "Vad försöker åklagaren göra under en rättegång?",
      options: [
        "Bevisa att den åtalade är skyldig",
        "Bestämma vem som blir domare",
        "Skriva en ny lag",
        "Bestämma vem som ska vara nämndeman"
      ],
      correctIndex: 0,
      explanationSv: "Under rättegången försöker åklagaren bevisa att den åtalade är skyldig.",
      chapter: 5,
      section: "Rättegång",
      sourcePage: 19,
      studyText: "Under rättegången försöker åklagaren bevisa att den åtalade är skyldig. Den åtalade har rätt till en försvarsadvokat.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-018",
      category: "lag_och_ratt",
      topic: "rattegang_straff",
      difficulty: "medium",
      question: "Vilka dömer tillsammans med domaren i tingsrätten?",
      options: ["Ministrar", "Nämndemän", "Poliser", "Kommunpolitiker"],
      correctIndex: 1,
      explanationSv: "I tingsrätten dömer nämndemän tillsammans med domaren.",
      chapter: 5,
      section: "Rättegång",
      sourcePage: 19,
      studyText: "I tingsrätten dömer nämndemän tillsammans med domaren. De ska representera allmänheten och ge insyn i rättsprocessen.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-019",
      category: "lag_och_ratt",
      topic: "rattegang_straff",
      difficulty: "easy",
      question: "Från vilken ålder är en person straffmyndig i Sverige enligt materialet?",
      options: ["12 år", "13 år", "15 år", "18 år"],
      correctIndex: 2,
      explanationSv: "En person är straffmyndig och kan bli åtalad för ett brott från 15 års ålder.",
      chapter: 5,
      section: "Straffmyndighet och belastningsregister",
      sourcePage: 19,
      studyText: "I Sverige är en person straffmyndig och kan bli åtalad för ett brott från 15 års ålder.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    },
    {
      id: "ch5-020",
      category: "lag_och_ratt",
      topic: "rattegang_straff",
      difficulty: "medium",
      question: "Vad kan hända med den som döms för vissa allvarliga brott?",
      options: [
        "Personen registreras i ett belastningsregister",
        "Personen förlorar automatiskt sitt medborgarskap",
        "Personen får aldrig arbeta igen",
        "Personen måste lämna Sverige"
      ],
      correctIndex: 0,
      explanationSv: "Den som döms för vissa allvarliga brott registreras i ett belastningsregister.",
      chapter: 5,
      section: "Straffmyndighet och belastningsregister",
      sourcePage: 19,
      studyText: "Den som döms för vissa allvarliga brott registreras i ett belastningsregister. Det kan göra det svårare att få jobb, körkort eller medborgarskap.",
      sourceVersion: "Sverige i fokus 2026-1, korrigerad 2026-08-10",
      active: true
    }
  ];

  window.SVERIGEQUIZ_QUESTIONS.push(...chapter5Questions);
})();
